name: Copilot Setup Steps

on:
  pull_request:

jobs:
  copilot-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backend setup - copy .env
        working-directory: ./backend
        run: cp .env.example .env

      - name: Composer install in backend
        working-directory: ./backend
        run: composer install

      - name: Generate Laravel key
        working-directory: ./backend
        run: php artisan key:generate

      - name: Run migrations and seed database
        working-directory: ./backend
        run: php artisan migrate --seed

      - name: NPM install in frontend
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build